services:
  api-aiops:
    build: .
    container_name: cerebro_aiops
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=postgresql://sre_user:sre_pass@db:5432/aiops
      - PYTHONUNBUFFERED=1
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: db_aiops
    environment:
      POSTGRES_USER: sre_user
      POSTGRES_PASSWORD: sre_pass
      POSTGRES_DB: aiops
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana_aiops
    ports:
      - "3001:3000"
    depends_on:
      - db
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/etc/grafana/dashboards
    restart: unless-stopped

volumes:
  postgres_data: