{
 "title": "AIOps Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  machine_id AS metric,\n  cpu_percent\nFROM metricas_infra\nWHERE\n  $__timeFilter(timestamp)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "RAM Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  machine_id AS metric,\n  ram_percent\nFROM metricas_infra\nWHERE\n  $__timeFilter(timestamp)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Alertas Recentes",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  machine_id,\n  log_alerta\nFROM metricas_infra\nWHERE\n  $__timeFilter(timestamp) AND log_alerta IS NOT NULL\nORDER BY 1 DESC\nLIMIT 50"
    }
   ]
  }
 ]
}